export const NotificationTypes = {
    STACK_NOTIFICATIONS: "STACK_NOTIFICATIONS",
    PUSH_NOTIFICATION: "PUSH_NOTIFICATION",
    REMOVE_NOTIFICATION: "REMOVE_NOTIFICATION",
    SEEN_NOTIFICATION: "SEEN_NOTIFICATION",
};
