export const PhotoActionTypes = {
    STACK_PHOTOS: "SET_PHOTOS",
    REMOVE_PHOTOS: "REMOVE_PHOTOS",
    FETCHING_PHOTOS: "FETCHING_PHOTOS",
    ADVANCE_PAGE: "ADVANCE_PAGE",
    SELECTED_PHOTO: "SELECTED_PHOTO",
    SWITCH_REACTION: "SWITCH_REACTION",
    REMOVE_SELECTED_PHOTO: "REMOVE_SELECTED_PHOTO",
    PUSH_COMMENT: "PUSH_COMMENT",
    STACK_COMMENTS: "STACK_COMMENTS",
};
