export const UserAction = {
    LIKE_A_PHOTO: "LIKE_A_PHOTO",
    UNLIKE_A_PHOTO: "UNLIKE_A_PHOTO",
    FOLLOW_A_USER: "FOLLOW_A_USER",
    UNFOLLOW_A_USER: "UNFOLLOW_A_USER",
    COMMENT_A_PHOTO: "COMMENT_A_PHOTO",
    UNCOMMENT_A_PHOTO: "UNCOMMENT_A_PHOTO"
}